name: smap
channels:
  - https://conda.anaconda.org/conda-forge/channel/main
  - defaults
dependencies:
  - basemap >=1.1.0,<2.0.0a
  - jupyter >=1.0.0,<2.0.0a
  - matplotlib <3.0.0a
  - numpy >=1.15.0,<2.0.0a
  - pandas >=0.23.4,<1.0.0a
  - pyproj 
  - python >=3.5.0,<4.0.0a
  - xarray >=0.10.9,<1.0.0a
  - requests >=2.21.0,<3.0.0a
